Repository lion-packages/route, pull requests merged in 2025-02, with the labels that each got.

#27 Update CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#28 Refactoring middleware and rule attributes
  phpstan.neon
  phpunit.xml
  public/index.php
  src/LionRoute/Dispatcher.php
  src/LionRoute/Interface/MiddlewareInterface.php
  src/LionRoute/Middleware.php
  src/LionRoute/Route.php
  tests/MiddlewareTest.php
  tests/Provider/ClassProvider.php
  tests/Provider/ControllerProvider.php
  tests/RouteTest.php
Labels: refactor, tests

#29 Fixed the execution of rules
  composer.json
  src/LionRoute/Dispatcher.php
  src/LionRoute/Kernel/Http.php
  src/LionRoute/Route.php
Labels: bug

#30 Dependencies have been updated
  composer.json
Labels: dependencies
