Repository lion-packages/route, pull requests merged in 2025-04, with the labels that each got.

#33 Add dependabot configuration
  .github/dependabot.yml
Labels: continuous integration

#34 Integrate Dependency-Review
  .github/workflows/php.yml
Labels: continuous integration

#35 Integrate PHPlint
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration

#36 The infection library is installed
  composer.json
  infection.json
  phpunit.xml
  src/LionRoute/Kernel/Http.php
  src/LionRoute/Route.php
  tests/Kernel/HttpTest.php
  tests/Provider/HttpProviderTrait.php
  tests/RouteTest.php
Labels: dependencies, tests

#37 Infection is integrated
  .github/workflows/php.yml
Labels: continuous integration

#38 Update README.md
  .github/README.md
Labels: documentation

#39 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#48 Added StyleCI configuration
  .styleci.yml
  tests/Attributes/RulesTest.php
  tests/Kernel/HttpTest.php
  tests/RouteTest.php
Labels: continuous integration, standardization

#43 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#41 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration
