Repository lion-packages/route, pull requests merged in 2025-01, with the labels that each got.

#22 Support for PHP 8.4
  .github/workflows/php.yml
  Dockerfile
  composer.json
  composer.lock
  src/LionRoute/Interface/HandlerResolverInterface.php
  src/LionRoute/Kernel/Http.php
  src/LionRoute/Middleware.php
  src/LionRoute/Route.php
  src/LionRoute/RouterResolver.php
Labels: continuous integration, dependencies

#23 Change action's name
  .github/workflows/php.yml
Labels: continuous integration

#24 Update LICENSE
  LICENSE
Labels: documentation

#25 Updated Github Actions settings
  .github/workflows/php.yml
  .gitignore
  Dockerfile
  composer.json
  composer.lock
  phpstan.neon
  phpunit.xml
  public/index.php
  src/LionRoute/Attributes/Rules.php
  src/LionRoute/Dispatcher.php
  src/LionRoute/Helpers/Rules.php
  src/LionRoute/Kernel/Http.php
  src/LionRoute/Middleware.php
  src/LionRoute/Route.php
  test.sh
  tests/Attributes/RulesTest.php
  tests/Helpers/RulesTest.php
  tests/Kernel/HttpTest.php
  tests/MiddlewareTest.php
  tests/Provider/ControllerProvider.php
  tests/Provider/HttpMethodsProviderTrait.php
  tests/Provider/HttpProviderTrait.php
  tests/RouteTest.php
  tests/build/coverage/.gitignore
  tests/build/logs/.gitignore
Labels: enhancement, continuous integration

#26 Documentation files have been relocated
  .github/CHANGELOG.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/README.md
Labels: documentation
